FROM python:3.12-slim

WORKDIR /tests

RUN apt-get update && \
    apt-get install -y \
        curl \
        git \
        && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN playwright install --with-deps

COPY . .

RUN chmod +x scripts/run-tests.sh

VOLUME ["/reports"]

ENTRYPOINT ["scripts/run-tests.sh"]