[pytest]
junit_family = xunit2
addopts = -ra
base_url = http://127.0.0.1:8080
testpaths = api_tests/tests ui_tests/tests
pythonpath = .

markers =
    smoke: critical fast tests used for PR and CI validation
    regression: broader test suite for full validation
    api: API-level tests
    ui: UI-level tests