name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install test framework dependencies
      run: |
        pip install -r requirements.txt

    - name: Install API dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sut/FastAPIMockApp/requirements.txt

    - name: Fix missing pytest deps
      run: |
        pip install pygments

    - name: Install Playwright Browsers
      run: |
        playwright install --with-deps

    - name: Start FastAPI App
      run: |
        cd sut/FastAPIMockApp
        nohup uvicorn app.main:app --host 127.0.0.1 --port 8080 > server.log 2>&1 &
        sleep 5

    - name: Verify API is running
      run: |
        curl -f http://127.0.0.1:8080/docs

    - name: Debug API
      run: |
        curl -X POST http://127.0.0.1:8080/api/login \
          -H "Content-Type: application/json" \
          -d '{"username":"admin", "password":"password"}'

    - name: Run Tests with Report
      run: |
        python -m pytest -v --env=dev --html=report.html --self-contained-html

    - name: Print server logs
      if: always()
      run: |
        cat server.log

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html